=== Overview
In this section we will build images that will be used through the remainder of the lab.  The Dockerfiles will be provided in the text below, just copy and paste them with the appropriate filenames. The Dockerfiles in this section are just examples.  Some are Fedora, some are RHEL.  Try them both out.

This section describes building the images, but doesn't go into detail on the usage.  That will be in the following chapters.

. Download the Dockerfiles and Scripts to each Atomic host and extract them.
+
----
curl -O https://raw.githubusercontent.com/scollier/project-atomic-lab-end-to-end/master/content/docker/dockerfiles.tar
tar -xf dockerfiles.tar
----
==== Apache Image Atomic Host 1
Build this image on Atomic Host 1
----
docker images
cd ~/Dockerfiles/atomic_host_1/apache
docker build -t demo/apache .
----

==== Apache Image Atomic Host 2
Build this image on Atomic Host 1
----
docker images
cd ~/Dockerfiles/atomic_host_2/apache
docker build -t demo/apache .
----

==== Mediawiki Image
Build this image on Atomic Host 1
. Build the image
----
docker images
cd ~/Dockerfiles/atomic_host_1/mediawiki
docker build -t demo/mediawiki .
----


==== MariaDB Image
Build this image on Atomic Host 1
. Build the image
----
docker images
cd ~/Dockerfiles/atomic_host_1/mariadb
docker build -t demo/mariadb .
----


==== nginx Image
Build this image on Atomic Host 1
. Build the image
----
docker images
cd ~/Dockerfiles/atomic_host_1/nginx
docker build -t demo/nginx .
----

==== MongoDB Image
Build this image on Atomic Host 1
. Build the image
----
docker images
cd ~/Dockerfiles/atomic_host_1/mongodb
docker build -t demo/mongodb .
----

==== Links
More example Dockerfiles are on the Fedora Cloud SIG github page:

https://github.com/fedora-cloud/Fedora-Dockerfiles


