=== Overview 

The rapid adoption of Docker demonstrates that the benefits of Docker and containers in general are valued by enterprise developers and administrators. Specifically, Docker and containers enable rapid application deployment by only including the minimal runtime requirements of the application. This minimal size and the mentality of replacing containers, rather than updating them, simplifies maintenance. Additionally, containers allow applications bring all of their runtime requirements with them, making them portable across multiple Red Hat Enterprise Linux environments. This means that containers can ease testing and troubleshooting efforts by providing a consistent runtime across development, QA and production environments. In addition, containers run applications in isolated memory, process, filesystem and networking spaces. The isolation ensures that any security breaches are limited to the container.

Red Hat has been investing in containers for a number of years in Red Hat Enterprise Linux and has been working on Docker in the upstream community since mid-2013. Red Hat's commitment to Docker and container technology is demonstrated not just in this background work, but also in the efforts to establish Docker containers as a standard part of the Red Hat Enterprise Linux environment. Red Hat has production experience leveraging container technologies like cgroups and namespaces since Red Hat Enterrise Linux 6. Establishing, consuming and sharing these capabilities as a part of Red Hat Enterprise Linux is a major step in making them consumable by enterprise customers.

This lab has 3 sections:

. Overview
. Lab 1: Docker Environment
. Lab 2: Containers can Talk

==== What you can expect to learn from this lab

Topics covered:

. Explore Docker
. Saving Content
. Host exploration
. External Logging
. Starting containers on boot
. Linking containers

==== Lab Environment

[NOTE]

Perform all activities on the Red Hat Enterprise Linux Atomic Host 1 unless instructed otherwise.

. SSH Access
+
----
ssh root@IPAddress_of_RHELAH1
----

=== Docker Overview
 
==== Explore Docker
All actions in this lab will performed by a user with root privileges.

. Check to ensure that SELinux is running on the host.
+    
----
getenforce
----
. Take a look at the documetation and general help as well as command specific help that is provide by the Docker package.
+
----
rpm -qd docker
man docker
man docker-run
docker --help
docker run --help
----

. A Docker _image_ is basically a layer.  A layer never changes.  Take a look at the images that are on this system.  There should be _nginx_,_mariadb_,mongodb,mediawiki,apache.
+
----
docker images --help
docker images
----
. Docker provides the _run_ option to run a image.  Check out the _run_ options and then run the image.  The following command launches the image, executes the command _echo hello_, and then exits.  
+
----
docker run --help
docker run fedora echo hello
----

. Check the logs.  The following commands will list the last container that ran so you can get the UUID and check the logs.  This should return the output of "echo hello".  Finally, run with the _-t_ option to allocate a psuedo-tty.  Note that _-l_ below is lowercase _L_.
+
----
docker ps -l    
docker logs <Container UUID>
----

. Tag the base image with a new name.
+
----
docker tag registry.access.redhat.com/redhat/rhel7beta rhel7
docker images | grep rhel7
----

. To run an interactive instance that you can look around in, pass the options _-i_ and _-t_. The _-i_ option starts an interactive terminal.  The _-t_ option allocates a pseudo-tty. You should see different results than before.  
+
----
docker run -i -t rhel7 bash
----
. Explore the _hosts_ file and look at the IP Address. Try some _ip_ commands... This is a slimmed down base image.  There are not many tools on here by default.  Exit the container when finished.
+
----
cat /etc/hosts
ip a
ip r
exit
----


. Switch to the Fedora image and take a look around. Grab the hostname of the container.  By default the hostname is set to the UUID of the container.  We will look at how to change that later.
+
----
docker run -i -t fedora bash
ip a 
ip r
hostname
----
. What processes are running inside the container?
+
----
ps aux
----
. What is the SELinux security label of the processes?
+
----
ps -Z
----

==== Saving Content

[NOTE] 
Perform these actions while still inside the Fedora container.


Now that we have an idea of what's going on inside the container, let's take a look at the process required to save a file.

. Create a file inside the container and see if it persists the next time you run the container.
+
----
echo "Hello World" >> ~/file1
ls ~/
----
. Exit the container.
+
----
exit
----
. Run the container again and check to see if the file exists.  The file should be gone.
+
----
docker run -i -t fedora bash
ls ~/
----
. Let's try this again and this time we'll commit the container.
+
----
echo "Hello World" >> ~/file2
----
. Exit the container and commit the container.
+
----
exit
docker ps -l
docker commit <Container UUID> file2/container
ae4b621fc73d0a66bf1e98657dee570043cb7f9910c0b96782a914fee85437f2
----
. Now lets see if it saved the file.  Now _docker images_ should show the newly commited container. Launch it again and check for the file.
+
----
docker images
docker run -i -t file2/container bash
ls ~/
exit
----
==== Host exploration

Now that we have explored what's on the inside of a container, let's see what is going on outside of the container.

. Let's launch a container that will run for a long time then confirm it is running.  The _-d_ option runs the container in daemon mode.  Remember, you can always get help with the options.  Run these commands on the host (you should not be inside a container at this time).
+
----
docker run --help
docker run -d rhel7 sleep 999999
----
. List the images that are currently running on the system.    
+
----
docker ps
----
. Now, check out the networking on the host. You should see the _docker0_ bridge and a _veth_ interface attached.  The _veth_ interface is one end of a virtual device that connects the container to the host machine. You should see that the IP address of the bridge is used as the default gateway of the container that you saw earlier.
+
----
ip a
----
. What are the firewall rules on the host?  You can see from the _nat_ table that all the traffic is masqueraded so that you can reach the outside world from the containers.
+
----
iptables -nvL
iptables -nvL -t nat
----
. What is Docker putting on the file system?  Check _/var/lib/docker_ to see what Docker actually puts down.
+
----
ls /var/lib/docker
----
    
. The root filesystem for the container is in the devicemapper directory.  Grab the _Container ID_ and complete the path below.  Replace <Container UUID> with the output from _docker ps -l_ and use tab completion to complete the <Container UUID>.
+
----
docker ps -l
ls /var/lib/docker/devicemapper/mnt/<Container ID><tab><tab>/rootfs
----
. How do I get the IP address of a running container? Grab the <Container UUID> of a running container.
+
----
docker ps
docker inspect <Container UUID>
----
. That is quite a lot of output, let's add a filter.  Replace <Container ID> with the output of _docker ps_.
+
----
docker ps
docker inspect --format '{{ .NetworkSettings.IPAddress }}' <Container UUID>
----
. Stop the container and check out its status. The container will not be running anymore, so it is not visible with _docker ps_.  To see the <Container ID> of a stopped container, use the _-a_ option.  The _-a_ option shows all containers, started or stopped.
+
----
docker stop <Container UUID>
docker ps
docker ps -a
----
    
  

==== Where are my logs?

The containers do not run syslog.  In order to get logs from the container, there are a couple of methods.  The first is to run the container with _/dev/log_ socket bind mounted inside the container.  The other is to write to external volumes.  That's in a later lab.  

. Launch the container with an interactive shell. The file _/dev/log_ is a socket.
+
----
docker run -v /dev/log:/dev/log -i -t rhel7 bash
----


. Now that the container is running.  Open another terminal and inspect the bind mount.  Do not run this inside the container.
+
----
docker ps -l
docker inspect --format '{{.Volumes}}' <Container UUID>
----
. Go back to the original terminal. Generate a message with _logger_ and exit the container.  This should write the message to the host journal.
+
----
logger "This is a log Entry"
exit
----
. Check the logs on the host to ensure the bind mount was successful.
+
----
journalctl | grep -i "This is a log Entry"
----
==== Control that Service!

We can control services with systemd.  Systemd allows us to start, stop, and control which services are enabled on boot, among many other things.  In this section we will use systemd to enable the _nginx_ service to start on boot.

. Have a look at the docker images.
+
----
docker images
----
. You will notice a repository called _demo/nginx_, that is what will be used in this section. 

. Here is the systemd unit file that needs to be created in order for this to work.  The content below needs to be placed in the _/etc/systemd/system/nginx.service_ file.  This is a trivial file that does not provide full control of the service.
+ 
--------
cat > /etc/systemd/system/nginx.service << EOF
[Unit]
Description=nginx server
After=docker.service

[Service]
Type=simple
ExecStart=/bin/bash -c '/usr/bin/docker start nginx || /usr/bin/docker run --name nginx -p 80:80 demo/nginx'

[Install]
WantedBy=multi-user.target
EOF
--------
. Now control the service.  Enable the service on reboot.
+
----
systemctl enable nginx.service
systemctl is-enabled nginx.service
----

. Start the service.  When starting this service, make sure there are no other containers using port 80 or it will fail.
+
----
docker ps
systemctl start nginx.service
docker ps
----
It's that easy!

. Before moving to the next lab, ensure that _nginx_ is stopped, or else there will be a port conflict on port 80.
+
----
docker ps | grep -i nginx
----
. If it is running:
+
----
docker stop nginx
systemctl disable nginx.service
----

        
=== Containers can Talk

Now that we have the fundamentals down, let's do something a bit more interesting with these containers.  This lab will cover launching a _MariaDB_ and _Mediawiki_ container. The two will be tied together via the Docker _link_ functionality.  This lab will build upon things we learned in lab 1 and expand on that.  We'll be looking at external volumes, links, and additional options to the Docker _run_ command.

**A bit about links**

Straight from the Docker.io site:

"Links: service discovery for docker. Links allow containers to discover and securely communicate with each other by using the flag -link name:alias  When two containers are linked together Docker creates a parent child relationship between the containers. The parent container will be able to access information via environment variables of the child such as name, exposed ports, IP and other selected environment variables."

=== MariaDB

This section shows how to set up an external volume and use hostnames when launching the MariaDB container.

==== Review the MariaDB Environment
. Review the scripts and other content that are required to build and launch the _MariaDB_ container.  This lab does not require that you build the container as it has already been done to save time.  Rather, it provides the information you need to understand what the requirements of building a container like this.
+
----
cd /root/Dockerfiles/atomic_host_1/mariadb/; ls
----

. Review the Dockerfile. Look at the _Dockerfile_. From the contents below, you can see that the Dockerfile is starting with the Fedora base image and is maintained by Scott Collier.  After the _FROM_ and _MAINTAINER_ commands are run, the commands to install software are run with _RUN_.  Think of the _RUN_ command as executing a line in a shell script.  After the software is installed we do some configuration of MariaDB. Next, we _ADD_ a basic MariaDB configuraiton file as well as a script that will be used to do more configuration and launch the database.  Finally _EXPOSE_ and _CMD_ which expose ports and provide the starting command, respectively.  Exposing the port will make the port available to the _Mediawiki_ container when it is launched with the _-link_ command.
+
----
MAINTAINER Scott Collier <scollier@redhat.com>

RUN yum -y install mariadb-server pwgen supervisor psmisc net-tools; yum clean all

RUN mkdir -p /var/log/mysql && \
    touch /var/log/mysql/.keep /var/lib/mysql/.keep && \
    chown -R mysql:mysql /var/log/mysql /var/lib/mysql

ADD ./simple.cnf /etc/my.cnf.d/
ADD ./config_mariadb.sh /config_mariadb.sh

EXPOSE 3306

CMD [ "/config_mariadb.sh" ]
----

. Review the _simple.cnf_ file. This configuraiton file has some basic settings for how we want to run the MariaDB container.
+
----
[client]
default-character-set  = utf8

[mysqld_safe]
nice		= 0
log-error=/var/log/mysql/mysqld.log

[server]
user		= mysql
tmpdir		= /tmp
skip-external-locking

max_connections		= 32
connect_timeout		= 5
wait_timeout		= 600
max_allowed_packet	= 16M
thread_cache_size       = 128
sort_buffer_size	= 4M
bulk_insert_buffer_size	= 16M
tmp_table_size		= 32M
max_heap_table_size	= 32M
myisam_recover          = BACKUP
key_buffer_size		= 128M
table_cache             = 400
myisam_sort_buffer_size	= 512M
concurrent_insert	= 2
read_buffer_size	= 2M
read_rnd_buffer_size	= 1M
query_cache_limit		= 128K
query_cache_size		= 64M
log_warnings		= 2
slow_query_log
slow_query_log_file		= /var/log/mysql/mariadb-slow.log
long_query_time = 10
log_slow_verbosity	= query_plan
log_slow_admin_statements
log_bin			= /var/log/mysql/mariadb-bin
log_bin_index		= /var/log/mysql/mariadb-bin.index
expire_logs_days	= 10
max_binlog_size         = 100M
default_storage_engine	= InnoDB
sql_mode		= NO_ENGINE_SUBSTITUTION,TRADITIONAL
innodb_log_file_size	= 16M
innodb_buffer_pool_size	= 265M
innodb_log_buffer_size	= 8M
innodb_file_per_table	= 1
innodb_open_files	= 400
innodb_io_capacity	= 400
innodb_flush_method	= O_DIRECT

[mysqldump]
quick
quote-names
max_allowed_packet	= 16M

[mysql]

[isamchk]
key_buffer		= 16M
----
. Review the config_mariadb.sh file. This script installs the database, sets permissions on some directories, creates a test database and assigns the appropriate access controls.  Of course, this is just an example and it can be heavily modified.
+
----
# cat config_mariadb.sh 
#!/bin/bash

__mysql_config() {
mysql_install_db
mkdir -vp /var/run/mariadb
chown -vR mysql:mysql /var/run/mariadb/
chown -R mysql:mysql /var/lib/mysql/
chown -R mysql:mysql /var/log/mariadb/
cd '/usr' ; /usr/bin/mysqld_safe --datadir='/var/lib/mysql' &
sleep 10

echo "Running the start_mysql function."
mysqladmin -u root password mysqlPassword
mysql -uroot -pmysqlPassword -e "UPDATE mysql.user SET Password=PASSWORD('mysqlPassword') WHERE User='root'; FLUSH PRIVILEGES;"
mysql -uroot -pmysqlPassword -e "GRANT ALL PRIVILEGES ON testdb.* TO 'testdb'@'localhost' IDENTIFIED BY 'mysqlPassword'; FLUSH PRIVILEGES;"
mysql -uroot -pmysqlPassword -e "GRANT ALL PRIVILEGES ON *.* TO 'testdb'@'%' IDENTIFIED BY 'mysqlPassword' WITH GRANT OPTION; FLUSH PRIVILEGES;"
mysql -uroot -pmysqlPassword -e "delete from user where user=''";
mysql -uroot -pmysqlPassword -e "GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' IDENTIFIED BY 'mysqlPassword' WITH GRANT OPTION; FLUSH PRIVILEGES;"
mysql -uroot -pmysqlPassword -e "select user, host FROM mysql.user WHERE Host <> 'localhost';"
sleep 10
killall mysqld
rm -f /var/lib/mysql/mysql.lock
exec /usr/libexec/mysqld
}

# Call all functions
__mysql_config

----    
==== Launch the MariaDB Container

. Either tail the audit log from your current terminal by placing the tail command in the background:
+
----
tail -f /var/log/audit/audit.log | grep -i avc &
----
. Or open another terminal and watch for AVCs in the foreground:
+
----
tail -f /var/log/audit/audit.log | grep -i avc
----
. Launch the container.  The /mariadb/db directory already exists and has database content inside.
+
----
docker run -p 3306:3306 -t -d --name mariadb -v /mariadb/db:/var/lib/mysql -v /mariadb/logs:/var/log/mariadb demo/mariadb
----
. Did the container start as expected?  You should see some AVC's.  Look at the logs on the container and see the _permission denied_ messages.
+
----
docker logs mariadb
----
. You will need to allow the proper SELinux permissions on the local _/mariadb/db_ directory so _MariaDB_ can access the directory.  Right now it's at _default_t_, this needs to be changed per below.  In addition, create the directory that we will use for the MariaDB log files and change it's SELinux permissions as well.
+
----
ls -lZd /mariadb/db
chcon -Rvt svirt_sandbox_file_t /mariadb/db/
ls -lZd /mariadb/db
mkdir -vp /mariadb/logs
chcon -Rvt svirt_sandbox_file_t /mariadb/logs/
----
. Now launch the container again.  Whether or not the container is still running, you will have to be removed because of a naming conflict.
+
----
docker ps -a
docker stop mariadb && docker rm mariadb
----
. Grab the database files for the lab and extract them.  The purpose of this is to create an environment that already exists.  By using these database files, the wiki will start right up.  Otherwise, you could just create the wiki from scratch.
+
----
cd /mariadb/db/
curl -O https://raw.githubusercontent.com/scollier/project-atomic-lab-end-to-end/master/content/docker/database_files.tar
tar xvf database_files.tar
cd
----
. Launch the container again.    
+
----
docker run -p 3306:3306 -t -d --name mariadb -v /mariadb/db:/var/lib/mysql -v /mariadb/logs:/var/log/mariadb demo/mariadb
docker ps -l
docker logs mariadb
----
. Take a look at the database files in _/mariadb/db/_ and also take a look at the log files in _/mariadb/logs/_.
+
----
ls /mariadb/db/*
tail -f /mariadb/logs/mariadb.log
----

The container should be running at this time. Kill the background _tail -f_ process if you want.

=== Mediawiki

This section shows how to launch the _Mediawiki_ container and link it back to the _MariaDB_ container.

==== Review the Mediawiki Environment

Review the scripts and other content that are required to build and launch the _Mediawiki_ container and link it to the _MariaDB_ container.  This lab does not require that you build the container as it has already been done in the prior lab.  Rather, it provides the information you need to understand what the requirements of building a container like this.  The files are pasted here, but they are also in _/root/Dockerfiles/atomic_host_1/mediawiki_


. Review the Dockerfile. This is a systemctl based dockerfile.  This is work being done so that the _wants_ files don't have to be removed.  At some point there will be a minimal systemd environment for containers. 
+
----
# cat Dockerfile 
FROM fedora:20
MAINTAINER Scott Collier <scollier@redhat.com>

ENV container docker

VOLUME [ "/sys/fs/cgroup" ]

RUN yum -y update; yum clean all
RUN yum -y install systemd mediawiki php php-mysqlnd httpd; yum clean all; \
(cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == systemd-tmpfiles-setup.service ] || rm -f $i; done); \
rm -f /lib/systemd/system/multi-user.target.wants/*;\
rm -f /etc/systemd/system/*.wants/*;\
rm -f /lib/systemd/system/local-fs.target.wants/*; \
rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
rm -f /lib/systemd/system/basic.target.wants/*;\
rm -f /lib/systemd/system/anaconda.target.wants/*; \
systemctl enable httpd.service
# yum -y erase iprutils

# Now wiki data.  We'll expose the wiki at $host/wiki, so the html root will be
# at /var/www/html/wiki; to allow this to be used as a data volume we keep the
# initialisation in a separate script.

ADD ./config.sh /config.sh
ADD ./LocalSettings.php /var/www/html/wiki/
RUN chmod +x /config.sh
RUN /config.sh

ADD run-mw.sh /run-mw.sh
RUN chmod +x /run-mw.sh

EXPOSE 80

CMD [ "/run-mw.sh" ]
----
. Review the config.sh script. Check the comments in the script.
+
----
#!/bin/bash
#
# The mediawiki rpm installs into /var/www/wiki.  We need to symlink this into
# the served /var/www/html/ tree to make them visible.
#
# Standard config will put these in /var/www/html/wiki (ie. visible at
# http://$HOSTNAME/wiki )

mkdir -p /var/www/html/wiki

cd /var/www/html/wiki
ln -sf ../../wiki/* .

# We want /var/www/html/wiki to be usable as a data volume, so it's
# important that persistent data lives here, not in /var/www/wiki.

chmod 711 .
rm -f images
mkdir images
chown apache.apache images

----
. Review the run-mw.sh script.  Check the comments in the script.
+
----
#!/bin/bash
#
# Run mediawiki in a docker container environment.

# If we are talking to a mariadb/mysql instance in a linked container
# (aliased "db" on port 3306), then we need to dynamically update the
# MW config to refer to the correct DB server IP address.
#
# Docker will set the DB_PORT_3306_TCP_ADDR env variable to the right
# IP in this case.
#
# We'll update lines like
#   $wgDBserver = "localhost";
# to point to the correct location.

if [ "x$DB_PORT_3306_TCP_ADDR" != "x" ] ; then
    # For initial configuration, it's also considerate to update the
    # default settings that drive the config screen defaults
    sed -i 's/^\$wgDBserver =.*$/\$wgDBserver = "'$DB_PORT_3306_TCP_ADDR'";/' /usr/share/mediawiki/includes/DefaultSettings.php

    # Only update LocalSettings if they already exist; on initial
    # setup they will not yet be here
    if [ -f /var/www/html/wiki/LocalSettings.php ] ; then
	sed -i 's/^\$wgDBserver =.*$/\$wgDBserver = "'$DB_PORT_3306_TCP_ADDR'";/' /var/www/html/wiki/LocalSettings.php
	sed -i 's/^\$wgServer =.*$/\$wgServer = "http:\/\/'$HOST_IP'";/' /var/www/html/wiki/LocalSettings.php
    fi
fi

# Finally fall through to the apache startup script that the apache
# Dockerfile (which we build on top of here) sets up

exec /usr/sbin/init
----


==== Launch the Mediawiki Container

This section show's how to use hostnames and link to an existing container.  Issue the _docker run_ command and link to the _mariadb_ container.

Run the container.  The command below is taking the enviroment variable _HOST_IP_ and will inject that into the _run-mw.sh_ script when the container is launched. The _HOST_IP_ is the IP address of the virtual machine that is hosting the container.  Replace IP_OF_VIRTUAL_MACHINE with the IP address of the virtual machine running the container.

[NOTE] 

In the following command, after the _-e_, leave the _HOST_IP_ entry.  It's used to hold the variable of the IP address of the Atomic Host 1 virtual machine.

----
ip a

docker run \
-e=HOST_IP=IP_OF_VIRTUAL_MACHINE \
--link mariadb:db \
-v /var/www/html/ \
--name mediawiki \
--privileged \
-p 80:80 \
-t \
-d \
-e 'container=docker' \
-v /sys/fs/cgroup:/sys/fs/cgroup:ro demo/mediawiki
----
. Explore the link that was made.
+
----
docker ps | grep media
----
[NOTE]

Notice in the _NAMES_ column on the mariadb container and how the link is represented.

. Inspect the container and get volume information:
+
----
docker inspect --format '{{ .Volumes }}' mediawiki
----
. Now take the output of the _docker inspect_ command and use the UUID from that in the next command.  Explore the mediawiki content.  This directory is mapped to _/var/www/html/wiki_ inside the container.
 +
----
ls /var/lib/docker/vfs/dir/<UUID Listed from Prior Query>/wiki
----   
. For example, see how the _LocalSettings.php_ file is there and has the correct content:
+
----
ls /var/lib/docker/vfs/dir/1c8c23c24ebaea8e00fb8639e545c662516445faee7dcd5d89882fdbf1fd638d/wiki
----
. Open browser on the host running the VM and confirm the configuration is complete.
+
----
firefox &
----
. Go to the _Mediawiki_ home page. Use the IP address of the virtual machine.  The same IP address that was passed in as the HOST_IP in the docker run command.
+
----
http://ip.address.here/wiki    
----
. Thats it.  Now you can start using your wiki. You can click on _Create Account_ in the top right and test it out, or log in with:
+
----
Username: admin
Passwrod: redhat
----

. Now, how did this work?  The way this works is that the Dockerfile _CMD_ command tells the container to launch with the _run-mw.sh_ script.  Here's the key thing about what that script is doing, let's review:
+
----
if [ "x$DB_PORT_3306_TCP_ADDR" != "x" ] ; then
    # For initial configuration, it's also considerate to update the
    # default settings that drive the config screen defaults
    sed -i 's/^\$wgDBserver =.*$/\$wgDBserver = "'$DB_PORT_3306_TCP_ADDR'";/' /usr/share/mediawiki/includes/DefaultSettings.php

    # Only update LocalSettings if they already exist; on initial
    # setup they will not yet be here
    if [ -f /var/www/html/wiki/LocalSettings.php ] ; then
    sed -i 's/^\$wgDBserver =.*$/\$wgDBserver = "'$DB_PORT_3306_TCP_ADDR'";/' /var/www/html/wiki/LocalSettings.php
    sed -i 's/^\$wgServer =.*$/\$wgServer = "http:\/\/'$HOST_IP'";/' /var/www/html/wiki/LocalSettings.php
    fi
fi
----
It's doing a check for an existing LocalSettings.php file.  We added that file during the Docker build process.  That file was copied to /var/www/html/wiki.  So, the script runs, sees that the file exists and points the _$wbDBserver_ variable to the MariaDB container.  So, no matter if these containers get shut down and have new IP addresses, the Mediawiki container will always be able to find the MariaDB container because of the _link_.  In addition, it's using the _-e_ option to pass environment variables, in this case, $HOST_IP to the _run-mw.sh_ script to complete the configuration.  

[NOTE]

Stop and delete the mediawiki and mariadb containers before moving forward.
