FROM 10.64.27.125:5000/rhel:7-0.0.1.beta.el7
# FROM 10.64.27.125:5000/vpavlin/rhel7
MAINTAINER scollier <scollier@redhat.com>

# Update the system
RUN yum -y update

# Install the troubleshooting software
RUN yum -y install nmap vim-enhanced net-tools telnet

# Add repo files
ADD ./mongo.repo /etc/yum.repos.d/
ADD ./mongodb.conf /etc/

# Install 
RUN yum -y install mongo-10gen-server mongo-10gen; yum clean all

# Expose ports
EXPOSE 27017 28017

CMD ["/usr/bin/mongod", "-f", "/mongo/config/mongodb.conf"]
