=== Options for Deployment

There are a few different ways to obtain Atomic images.

. In .qcow2 format
. Deploy from rpm

For the purposes of this lab, we will be deploying Red Hat Enterprise Linux Atomic Controllers via the .qcow2 pre-built images.

=== Obtaining the images

. On the host running the VM's, create the directory structure.
+
----
cd ~
mkdir -p /var/lib/libvirt/images/atomic/{1,2}
----
. Download and decompress the images to the appropriate directories.  You only need to do the following step if the images haven't been downloaded for you already.
+
----
cd ~
pushd /var/lib/libvirt/images/atomic/1/
wget http://rcm-img06.build.bos.redhat.com/images/auto/rh-atomic-controller-el7-x86_64-buildmaster-controller-docker/latest-qcow2.xz
xz -d latest-qcow2.xz
cp latest-qcow2 ../2/
popd 


----
. Install the image and create an additional drive
+
----
cd ~
for i in 1 2; do 
	sudo virt-install \
	--memory 2048 \
	--name Atomic_Host_$i \
	--disk /var/lib/libvirt/images/atomic/$i/latest-qcow2 \
	--import \
	--noautoconsole \
	--disk /var/lib/libvirt/images/atomic/$i/storage_$i.qcow2,format=qcow2,sparse=true,size=10; 
done
----
. Set a password for the _root_ user on each Atomic host.
. Get IP Address of both hosts and open up a terminal console to each machine.  

=== Configure Disk Partitions
The Red Hat Enterprise Linux Atomic Controllers come with a fairly small disk image.  We need to confiure the second disk that was added with _virt-install_ and mount that under _/var/lib/docker_.
[NOTE]
[yellow-background]#Ensure you are on the correct host!  It would not be good if you are on the wrong host.  You should be on the Atomic VM's when you perform the following operation.#

. Create the Atomic_Host_sdb.layout file that will be used to partition _sdb_.  You can just copy the following contents into your shell on the Atomic Host VM's.
+
----
cat << EOF > Atomic_Host_sdb.layout
# partition table of /dev/sdb
unit: sectors

/dev/sdb1 : start=     2048, size= 20969472, Id=83
/dev/sdb2 : start=        0, size=        0, Id= 0
/dev/sdb3 : start=        0, size=        0, Id= 0
/dev/sdb4 : start=        0, size=        0, Id= 0
EOF

sfdisk /dev/sdb < Atomic_Host_sdb.layout
----
. Format _/dev/sdb1_
+
----
mkfs.xfs /dev/sdb1
----
. Ensure that only _/dev/sdb1_ is mounted to _/var/lib/docker_
+
----
systemctl stop docker
mount
df -hal
umount /var/lib/docker
mount /dev/sdb1 /var/lib/docker
mount
----
. Get the UUID from _/dev/sdb1_ and add it to the _/etc/fstab_
+
----
cp /etc/fstab{,.orig}
cat /etc/fstab
echo "$(blkid /dev/sdb1 | awk '{ print $2 }') /var/lib/docker xfs defaults 1 1" >> /etc/fstab
cat /etc/fstab
mount -a
mount
df -hal
systemctl start docker
ls /var/lib/docker
----

=== Validate Hostname and Networking
. Set the hostname for each of your Red Hat Enterprise Linux Atomic Controller's.  
+
----
hostnamectl set-hostname atomic1.local     # on host 1
hostnamectl set-hostname atomic2.local     # on host 2
----
. Ensure you can ping the other controller

=== Validate SELinux
. Ensure that selinux is set to enforcing mode on each controller.
+
----
getenforce
----

=== Ensure Docker and geard are Functional
+
----
systemctl status docker
systemctl status geard
----
=== Upgrade both controllers. 
. Disable GPG support
+
----
echo "gpg-verify=false" >> /ostree/repo/config
----
. Run the following on both of the Atomic controllers.
+
----
rpm-ostree upgrade
reboot
----
