== geard
geard is a Docker container orchestration tool.  At the currrent release, it essentially does three things:

. SSH
. Multiple container deployment
. Link

=== geard Lab Prerequisites
. Two Atomic hosts
+
----
hostname   # on host 1
hostname   # on host 2
----
. Check to see that geard and Docker are installed and running
+
----
rpm -qa | grep -i geard
rpm -qa | grep -i docker
systemctl status geard
systemctl status docker
----
. Check for the proper .json files in the users home directory
+
----
ls *.json
http_single.json  mongo_deploy.json
----


=== Part 1. Deploy a Single Container +
{empty} +

*On host 1:*

. Check which units geard has registered
+
----
gear list-units
----
. Check to see which images are available and running within Docker
+
----
docker images
docker ps
----
. Install the first unit
+
----
gear install demo/apache web-server --start -p 80:80
----
. List the units again
+
----
gear list-units
----
. Show the container is also recognized by Docker
+
----
docker ps
----
. Make sure the web server is responding to requests
+
----
curl http://localhost
----
. List the units one more time
+
----
gear list-units
----
. Clean up the environmentnd
+
----
gear delete web-server
gear list-units
----


=== Part 2. Deploy Multiple Containers on a Single Host
{empty} +

*On host 1:*

. Check the geard environment
+
----
gear list-units
docker ps
----
. Check out the _http_single_HTB.json_ file 
+
----
cat http_single_HTB.json
{
  "Containers": [
    {
      "Name": "web-server",
      "Image": "demo/apache",
      "PublicPorts": [
        {
          "Internal": 80
        }
      ],
      "Links": [
        {
          "To": "web-server",
          "NonLocal": true,
          "MatchPort": true
        }
      ],
      "Count": 3
    }
  ],
  "IdPrefix": "",
  "RandomizeIds": false
}
----
This file tells geard to deploy an application with _Name_ "web-server", to use _image_ "demo/apache" with an internal port of 80 and a count of 3.

. Check out the _/var/lib/containers/_ directory.  This is where geard stores it's content. Right now there will not be any content in the _units_ directory.  After a successful launch of the application there will be.
+
----
ls /var/lib/containers/
ls /var/lib/containers/units/
----
. Deploy the application. This tells geard to deploy all three web servers on the same host.
+
----
gear deploy http_single_HTB.json
----
. Check the _/var/lib/containers/_ directory again to see what content geard added
+
----
ls /var/lib/containers/
ls /var/lib/containers/units/
----
. Check _systemd_ integration
+
----
systemctl status ctr-web-server-1
----
. Check to ensure the web servers are registered with geard and Docker
+
----
gear list-units
docker ps
----
. Now that we have the ports listed as shown in _docker ps_, let's make sure one of the web servers are running.
+
----
curl http://localhost:4000
----
. Clean up the environment
+
----
gear list-units
gear delete web-server{1,2,3}
gear list-units
docker ps
----


=== Part 3. Deploy a MongoDB replica set on a single host
{empty} +

*On host 1:*
. Check the environment
+
----
gear list-units
docker ps
----
. Explore the _mongo_deploy.json_, notice the name, count and image.  The .json file is also taking care of the linking.
+
----
cat mongo_deploy.json
{
  "containers":[
    {
      "name":"db",
      "count":3,
      "image":"demo/mongo",
      "publicports":[
        {"internal":27017,"external":0}
      ],
      "links":[
        {"to":"db","nonlocal":true,"matchport":true}
      ]
    }
  ]
}
----
. Deploy the application
+
----
gear deploy mongo_deploy.json
----
. List the units and container
+
----
gear list-units
docker ps
----
. Connect with the MongoDB client
+
----
mongo --host localhost --port "PUT PORT HERE"
----
. Copy in the configuration file
+
----
cat mongo_replica_json 
cfg = {
    "_id" : "replica0",
    "version" : 1,
    "members" : [
        {
            "_id" : 0,
            "host" : "192.168.1.1:27017"
        },
        {
            "_id" : 1,
            "host" : "192.168.1.2:27017"
        },
        {
            "_id" : 2,
            "host" : "192.168.1.3:27017"
        },
    ]
}
----
. Initiate the replica set
+
----
> rs.initiate(cfg)
----
. Refresh the configuration until you see PRIMARY and SECONDARY
+
----
> rs.status()
> rs.status()
> rs.status()
----
. Clean up the environment
+
----
gear list-units
docker ps
gear delete db-{1,2,3}
gear list-units
docker ps
----























