=== geard
geard is a Docker container orchestration tool.  At the currrent release, it essentially does three things:

. SSH
. Multiple container deployment
. Link

This lab has 5 parts.

. Single host / single container deployment
. Single host / multi container deployment
. Single host / MongoDB replica set configuration
. Multi host container linking
. SSH enablement for contianers

=== geard Lab Prerequisites
. Two Atomic hosts
+
----
hostname   # on host 1
hostname   # on host 2
----
. Copy down the json files to both hosts.  Open a terminal session to each host and complete the following.
+
----
cd

for i in http_single.json mongo_deploy.json mongo_replica.json; do
	curl -O https://raw.githubusercontent.com/scollier/project-atomic-lab-end-to-end/master/content/geard/$i
done
----
. Check to see that geard and Docker are installed and running
+
----
rpm -qa | grep -i geard
rpm -qa | grep -i docker
systemctl status geard
systemctl status docker
----
. Check for the proper .json files in the users home directory
+
----
ls *.json
http_single.json  mongo_deploy.json  mongo_replica.json
----


=== Deploy a Single Container +

*On Atomic Host 1:*

. Check which units geard has registered
+
----
gear list-units
----
. Check to see which images are available and running within Docker
+
----
docker images
docker ps
----
. Install the first unit
+
----
gear install demo/mongodb mongodb --start -p 27017:27017
----
. List the units again
+
----
gear list-units
----
. Show the container is also recognized by Docker
+
----
docker ps
----
. Make sure the MongoDB server is responding to requests.  It will notify you that you are trying to access the database over the native driver port.  Just ignore it, we are just making sure it is listening.
+
----
curl http://localhost:27017
----
. List the units one more time
+
----
gear list-units
----
. Clean up the environment
+
----
gear delete mongodb
gear list-units
docker ps
----

=== Deploy a MongoDB replica set on a single host

*On host 1:*

. Check the environment
+
----
gear list-units
docker ps
----
. Explore the _mongo_deploy.json_, notice the name, count and image.  The .json file is also taking care of the linking.
+
----
cd

cat mongo_deploy.json
{
  "containers":[
    {
      "name":"db",
      "count":3,
      "image":"demo/mongodb",
      "publicports":[
        {"internal":27017,"external":0}
      ],
      "links":[
        {"to":"db","nonlocal":true,"matchport":true}
      ]
    }
  ]
}
----
. Deploy the application
+
----
# gear deploy mongo_deploy.json 
==> Deploying mongo_deploy.json
ports: searching block 41, 4000-4099
ports: Reserved port 4000
local PortMapping: 27017 -> 4000
local Container db-1 is installed
ports: Reserved port 4001
local PortMapping: 27017 -> 4001
local Container db-2 is installed
ports: Reserved port 4002
local PortMapping: 27017 -> 4002
local Container db-3 is installed
==> Linking db: 192.168.1.1:27017 -> localhost:4000
==> Linking db: 192.168.1.2:27017 -> localhost:4001
==> Linking db: 192.168.1.3:27017 -> localhost:4002
local Container db-1 starting
local Container db-2 starting
local Container db-3 starting
==> Deployed as mongo_deploy.json.20140605-203024
----
. Copy the contents of the replica set file and paste that into the mongodb shell, which you will be launching in the next step.
+
----
cat ~/mongo_replica.json 
cfg = {
    "_id" : "replica0",
    "version" : 1,
    "members" : [
        {
            "_id" : 0,
            "host" : "192.168.1.1:27017"
        },
        {
            "_id" : 1,
            "host" : "192.168.1.2:27017"
        },
        {
            "_id" : 2,
            "host" : "192.168.1.3:27017"
        },
    ]
}
----
. List the units and container
+
----
gear list-units
docker ps
----
. This lab does require that you have the MongoDB client installed on a workstation that can access this VM. Connect with the MongoDB client. Install the _mongodb_ package.  The PORT that you are connecting to on the next step is the port that _geard_ mapped.  Most likely 400x.  Replace _IP_OF_VM_ with the IP address of the host running the MongoDB replica set.  This should the IP Address Atomic Host 1.  Connect to the first MongoDB server, this should be running on port 4000.
+
----
mongo --host IP_OF_VM --port "PUT PORT HERE"
----
. Paste the contents of the replica configuration file in here. Initiate the replica set
+
----
> rs.initiate(cfg)
{
        "info" : "Config now saved locally.  Should come online in about a minute.",
        "ok" :
}
----
. Refresh the configuration until you see PRIMARY and SECONDARY replica set members.  Below is an example of what it looks like when working.
+
----
> rs.status()
> rs.status()
> rs.status()
replica0:PRIMARY> rs.status()
{
        "set" : "replica0",
        "date" : ISODate("2014-06-05T13:19:09Z"),
        "myState" : 1,
        "members" : [
                {
                        "_id" : 0,
                        "name" : "192.168.1.1:27017",
                        "health" : 1,
                        "state" : 1,
                        "stateStr" : "PRIMARY",
                        "uptime" : 255,
                        "optime" : Timestamp(1401974323, 1),
                        "optimeDate" : ISODate("2014-06-05T13:18:43Z"),
                        "electionTime" : Timestamp(1401974336, 1),
                        "electionDate" : ISODate("2014-06-05T13:18:56Z"),
                        "self" : true
                },
                {
                        "_id" : 1,
                        "name" : "192.168.1.2:27017",
                        "health" : 1,
                        "state" : 2,
                        "stateStr" : "SECONDARY",
                        "uptime" : 25,
                        "optime" : Timestamp(1401974323, 1),
                        "optimeDate" : ISODate("2014-06-05T13:18:43Z"),
                        "lastHeartbeat" : ISODate("2014-06-05T13:19:08Z"),
                        "lastHeartbeatRecv" : ISODate("2014-06-05T13:19:08Z"),
                        "pingMs" : 0,
                        "syncingTo" : "192.168.1.1:27017"
                },
                {
                        "_id" : 2,
                        "name" : "192.168.1.3:27017",
                        "health" : 0,
                        "state" : 8,
                        "stateStr" : "SECONDARY",
                        "uptime" : 0,
                        "optime" : Timestamp(0, 0),
                        "optimeDate" : ISODate("1970-01-01T00:00:00Z"),
                        "lastHeartbeat" : ISODate("2014-06-05T13:19:08Z"),
                        "lastHeartbeatRecv" : ISODate("1970-01-01T00:00:00Z"),
                        "pingMs" : 0
                        "syncingTo" : "192.168.1.1:27017"
                }
        ],
        "ok" : 1
}
----

. Explore the replica set a bit more.
+
----
docker logs db-1
docker logs db-1
docker logs db-3
gear status db-1
systemctl status ctr-db-2
----

. Clean up the environment
+
----
gear list-units
docker ps
gear delete db-{1,2,3}
gear list-units
docker ps
----


=== Multi-host Application Linking - SKIP THIS SECTION, IT NEEDS WORK

*On host 1:*

. Check the environment
+
----
gear list-units
docker ps
----
. Explore the _http_single.json_ file
+
----
cat http_single.json
{
  "Containers": [
    {
      "Name": "web-server",
      "Image": "demo/apache",
      "PublicPorts": [
        {
          "Internal": 80
        }
      ],
      "Links": [
        {
          "To": "web-server",
          "NonLocal": true,
          "MatchPort": true
        }
      ],
      "Count": 2
    }
  ],
  "IdPrefix": "",
  "RandomizeIds": false
}
----
. Ensure that the geard and Docker daemons are running on the second host.
+
----
systemctl status docker  # on host 1
systemctl status docker  # on host 2
systemctl status geard  # on host 1
systemctl status geard  # on host 2
----
. Deploy the application on both hosts, where *x.x.x.x* is the IP address of the second host
+
----
gear deploy http_single.json localhost x.x.x.x
----
. List the units and containers on both hosts
+
----
gear list-units    # on host 1
gear list-units    # on host 2
docker ps          # on host 1
docker ps          # on host 2
----
. On host 1, get the pid for the web server container
+
----
docker inspect --format '{{ .State.Pid }}' <container uid>
----
. Use _nsenter_ to enter the namespace of the PID and take a look at the IPtables rules. You will see that there is a rule forwarding all traffic to _192.168.1.x_ to the external port on the localhost and the external port on the remote host.  Basically geard is telling the container that every application is local.
+
----
nsenter -m -u -n -i -p -t <PID FROM <container uid>> bash
iptables -nvL -t nat
----
. Ensure that you can get the index.html from each host 
+
----
curl http://localhost:<external port localhost>
curl http://localhost:<external port remote host>
----
. On host 2, ensure that you can pull that web page as well and compare to the output that you got inside the container on host 1
+
----
docker ps
curl http://localhost:<external port localhost>
----
. Clean up the environment
+
----
gear list-units   # on host 1
gear list-units   # on host 2
gear delete web-server-1    # on host 1
gear delete web-server-2    # on host 2
----


=== SSH Enablement for Containers

*On host 1:*

TBD

