=== Asciidoc

Please refer to the asciidoc user's guide: http://asciidoctor.org/docs/asciidoc-writers-guide/

This cheat sheet is also very helpful: http://powerman.name/doc/asciidoc

==== Setup on Linux
Git quick start: https://engineering.redhat.com/trac/refarch/wiki/GITConfig

. yum install git asciidoc docbook-xsl fop
. Edit /etc/asciidoc/asciidoc.conf and change the following
+
----
iconsdir=./images/icons
----
+
To:
+
----
iconsdir=/etc/asciidoc/images/icons
----

==== Compiling ASCIIDOC documents
* To create a single HTML document: asciidoc <text file>

* To create HTML Slides: asciidoc --backend slidy <text file>

* To create a PDF:  a2x -fpdf -dbook --fop --no-xmllint -v <asciidoc file>

* To create an EPUB: a2x -fepub -dbook --no-xmllint -v <asciidoc file>

==== Hello World
Create a simple asciidoc document:

hello_world.adoc
----
= My Document Title
:data-uri:
:icons:
:toc:

== Chapter 1
some content

== Chapter 2
some more content
----

==== Automatic Compiling
Use a Makefile to 

Makefile
----
DOCS=hello_world.adoc

all: $(DOCS) html pdf epub

html: $(DOCS)
	asciidoc -v bootcamp-labs.adoc

pdf: $(DOCS)
	a2x -fpdf -dbook --fop --no-xmllint -v bootcamp-labs.adoc

epub: $(DOCS)
	a2x -fepub -dbook --no-xmllint -v bootcamp-labs.adoc

clean:
	rm -f *.html *.pdf *.epub
----


Compile the doc
----
make clean && make
----

=== Git
. create github account and associated red hat email
. settings -> ssh keys -> add ssh keys 
. paste public key (ssh-key-gen if you need one)
. Fork the repo: https://github.com/vvaldez/rhel-osp-tigerteam-cubs
. Clone your forked repo:
+
----
git clone git@github.com:<YOUR_NAME_HERE>/rhel-osp-tigerteam-cubs.git
----
+
. Set your master branch to have a remote branch on your origin (your github fork)
+
----
git branch --set-upstream-to=origin/master master
----
+
. Set a remote of upstream to be the original project that was forked
+
----
git remote add upstream git@github.com:vvaldez/rhel-osp-tigerteam-cubs.git
----
+
. create branch: 
+
----
git checkout -b <branch>
----
. make changes. For this lab add your name to the file "completed.lab"
. test changes and verify
+
----
git diff
----
+
. Add files that will be committed
+
----
git add completed.lab <other_files>
----
+
. Commit changes
+
----
git commit
----
+
. Push to a remote branch on your origin (your github fork)
+
----
git push --set-upstream origin <branch name>
----
+
. You may need to add this option (git will tell you)
+
----
git config --global push.default simple
----
+
Push change to your remote branch (on your github fork)
+
----
git push
----
+
. Go to github.com and initial pull request
. After pull request is approved pull changes. First fetch the latest upstream
+
----
git fetch upstream
----
+
. Rebase against the upstream master branch
+
----
git rebase upstream/master
----
